ALTER TABLE `rides` DROP `contact`;
ALTER TABLE `rides` ADD `dateNEW` DATE NULL DEFAULT NULL AFTER `date`;
UPDATE `rides` SET `dateNEW` = DATE_ADD(DATE_ADD(FROM_UNIXTIME(0), INTERVAL `date` SECOND), INTERVAL 1 DAY);
ALTER TABLE `rides` DROP `date`;
ALTER TABLE  `rides` CHANGE  `dateNEW`  `date` DATE NULL DEFAULT NULL;
